// ═══════════════════════════════════════════════════════════════════════════════
// SERVER-SIDE CATEGORIES — includes rankValue (5th element) for objective ranking
// rankValue is NEVER sent to clients during gameplay, only after both submit.
// Format: [displayName, description, emoji, wikiKey, rankValue]
// ═══════════════════════════════════════════════════════════════════════════════

module.exports = {
  filme: {
    name: 'Filme', emoji: '🎬',
    criterion: 'IMDb-Bewertung',
    criterionDesc: 'Sortiere nach IMDb-Bewertung (höchste = Platz 1)',
    items: [
      ['Der Pate', '1972 · Francis Ford Coppola. Saga der Corleone-Familie — einer der einflussreichsten Filme aller Zeiten.', '🎭', 'The Godfather', 9.2],
      ['Pulp Fiction', '1994 · Quentin Tarantino. Verschachtelte Gangster-Geschichten mit ikonischen Dialogen.', '💼', 'Pulp Fiction', 8.9],
      ['Titanic', '1997 · James Cameron. Liebesgeschichte auf dem berühmtesten Schiff der Welt. 11 Oscars.', '🚢', 'Titanic (1997 film)', 7.9],
      ['The Dark Knight', '2008 · Christopher Nolan. Heath Ledgers legendäre Joker-Performance.', '🦇', 'The Dark Knight', 9.0],
      ['Schindlers Liste', '1993 · Steven Spielberg. Oskar Schindler rettete über 1.000 Juden.', '✡️', "Schindler's List", 9.0],
      ['Inception', '2010 · Christopher Nolan. Ein Dieb stiehlt Geheimnisse aus Träumen in Träumen.', '🌀', 'Inception', 8.8],
      ['Forrest Gump', '1994 · Robert Zemeckis. Ein einfacher Mann erlebt die wichtigsten Momente der US-Geschichte.', '🏃', 'Forrest Gump', 8.8],
      ['Matrix', '1999 · Wachowskis. Was, wenn die Realität nur eine Simulation ist?', '💊', 'The Matrix', 8.7],
      ['Fight Club', '1999 · David Fincher. Ein Büroangestellter gründet einen Underground-Kampfclub.', '👊', 'Fight Club (film)', 8.8],
      ['Der Herr der Ringe', '2001–03 · Peter Jackson. Frodos Reise zum Schicksalsberg. 17 Oscars.', '💍', 'The Lord of the Rings (film series)', 9.0],
      ['Star Wars', '1977 · George Lucas. Die Weltraum-Saga, die die Popkultur für immer veränderte.', '⭐', 'Star Wars (film)', 8.6],
      ['Interstellar', '2014 · Nolan. Ein Astronaut reist durch ein Wurmloch, um die Menschheit zu retten.', '🕳️', 'Interstellar (film)', 8.7],
      ['Gladiator', '2000 · Ridley Scott. Ein römischer General kämpft als Gladiator um Rache.', '⚔️', 'Gladiator (2000 film)', 8.5],
      ['Jurassic Park', '1993 · Spielberg. Dinosaurier werden zum Leben erweckt — und brechen aus.', '🦖', 'Jurassic Park (film)', 8.2],
      ['Avatar', '2009 · James Cameron. Auf Pandora kämpft ein Marine für die Na\'vi. Höchstes Einspielergebnis.', '🌿', 'Avatar (2009 film)', 7.9],
      ['Goodfellas', '1990 · Scorsese. Aufstieg und Fall des Mafia-Mitglieds Henry Hill.', '🔫', 'Goodfellas', 8.7],
      ['The Shawshank Redemption', '1994 · Darabont. Andy Dufresne plant 19 Jahre lang seine Flucht.', '🔑', 'The Shawshank Redemption', 9.3],
      ['Joker', '2019 · Todd Phillips. Düstere Entstehungsgeschichte von Batmans Erzfeind. Oscar für Joaquin Phoenix.', '🃏', 'Joker (2019 film)', 8.4],
      ['Django Unchained', '2012 · Tarantino. Ein befreiter Sklave zieht als Kopfgeldjäger durch den Westen.', '🤠', 'Django Unchained', 8.4],
      ['Avengers: Endgame', '2019 · Das große Finale des Marvel Cinematic Universe.', '🦸', 'Avengers: Endgame', 8.4],
      ['The Wolf of Wall Street', '2013 · Scorsese. Jordan Belforts exzessiver Lebensstil an der Börse.', '💰', 'The Wolf of Wall Street (2013 film)', 8.2],
      ['Zurück in die Zukunft', '1985 · Zemeckis. Marty McFly reist mit einem DeLorean durch die Zeit.', '⏰', 'Back to the Future', 8.5],
      ['Inglourious Basterds', '2009 · Tarantino. Jüdische Kommandoeinheit jagt Nazis im besetzten Frankreich.', '🎖️', 'Inglourious Basterds', 8.3],
      ['Whiplash', '2014 · Chazelle. Junger Schlagzeuger und sein besessener Lehrer. Duell um Perfektion.', '🥁', 'Whiplash (2014 film)', 8.5],
      ['Parasite', '2019 · Bong Joon-ho. Arme Familie infiltriert reichen Haushalt. Erster nicht-englischer Oscar-Gewinner.', '🏠', 'Parasite (2019 film)', 8.5],
      ['Shutter Island', '2010 · Scorsese. US-Marshal ermittelt in einer Psychiatrie — nichts ist, wie es scheint.', '🏝️', 'Shutter Island (film)', 8.2],
      ['Catch Me If You Can', '2002 · Spielberg. Wahre Geschichte des Hochstaplers Frank Abagnale Jr.', '✈️', 'Catch Me If You Can', 8.1],
      ['Das Leben ist schön', '1997 · Benigni. Ein Vater schützt seinen Sohn im KZ mit Fantasie und Humor.', '🌟', 'Life Is Beautiful', 8.6],
    ],
  },

  serien: {
    name: 'Serien', emoji: '📺',
    criterion: 'IMDb-Bewertung',
    criterionDesc: 'Sortiere nach IMDb-Bewertung (höchste = Platz 1)',
    items: [
      ['Breaking Bad', '2008–13 · 5 Staffeln. Chemielehrer wird Drogenbaron. Oft beste Serie aller Zeiten.', '🧪', 'Breaking Bad', 9.5],
      ['Game of Thrones', '2011–19 · 8 Staffeln. Intrigen, Drachen und Krieg um den Eisernen Thron.', '🐉', 'Game of Thrones', 9.2],
      ['Stranger Things', '2016– · Netflix. Kinder in den 80ern kämpfen gegen Monster aus einer Paralleldimension.', '🔦', 'Stranger Things', 8.7],
      ['The Office', '2005–13 · 9 Staffeln. Mockumentary über den Büroalltag bei Dunder Mifflin.', '📎', 'The Office (American TV series)', 9.0],
      ['Friends', '1994–04 · 10 Staffeln. Sechs Freunde in New York — Sitcom-Ikone einer Generation.', '☕', 'Friends', 8.9],
      ['Dark', '2017–20 · 3 Staffeln. Deutsche Netflix-Serie über Zeitreisen in einer Kleinstadt.', '⏳', 'Dark (TV series)', 8.8],
      ['The Sopranos', '1999–07 · 6 Staffeln. Mafia-Boss zwischen Verbrechen und Therapie.', '🎰', 'The Sopranos', 9.2],
      ['The Wire', '2002–08 · 5 Staffeln. Jede Staffel beleuchtet einen anderen Aspekt Baltimores.', '📡', 'The Wire', 9.3],
      ['Chernobyl', '2019 · Mini-Serie. Erschütternde Rekonstruktion der Atomkatastrophe von 1986.', '☢️', 'Chernobyl (miniseries)', 9.4],
      ['Peaky Blinders', '2013–22 · 6 Staffeln. Shelby-Gang kontrolliert Birmingham in den 1920ern.', '🎩', 'Peaky Blinders (TV series)', 8.8],
      ['Narcos', '2015–17 · 3 Staffeln. Pablo Escobar und das kolumbianische Drogenkartell.', '🍃', 'Narcos', 8.8],
      ['Better Call Saul', '2015–22 · 6 Staffeln. Wie Jimmy McGill zu Saul Goodman wurde.', '⚖️', 'Better Call Saul', 9.0],
      ['The Mandalorian', '2019– · Disney+. Kopfgeldjäger und Baby Yoda im Star-Wars-Universum.', '🪖', 'The Mandalorian', 8.7],
      ['The Crown', '2016–23 · 6 Staffeln. Das Leben von Queen Elizabeth II.', '👑', 'The Crown (TV series)', 8.6],
      ['Vikings', '2013–20 · 6 Staffeln. Ragnar Lothbrok und die legendären Wikinger-Raubzüge.', '⚓', 'Vikings (TV series)', 8.5],
      ['Squid Game', '2021– · Netflix. 456 Spieler kämpfen in tödlichen Kinderspielen um Milliarden.', '🦑', 'Squid Game', 8.0],
      ['The Witcher', '2019– · Netflix. Geralt von Riva jagt Monster in einer düsteren Fantasywelt.', '🗡️', 'The Witcher (TV series)', 8.0],
      ['Money Heist', '2017–21 · 5 Staffeln. Genialer Professor plant den größten Raubüberfall Spaniens.', '🎭', 'Money Heist', 8.2],
      ['Sherlock', '2010–17 · 4 Staffeln. Cumberbatch als moderner Sherlock Holmes im heutigen London.', '🔍', 'Sherlock (TV series)', 9.1],
      ['House of Cards', '2013–18 · 6 Staffeln. Frank Underwood manipuliert sich zum US-Präsidenten.', '🏛️', 'House of Cards (American TV series)', 8.6],
      ['True Detective', '2014– · Staffel 1 mit McConaughey & Harrelson gilt als eine der besten überhaupt.', '🔎', 'True Detective', 8.9],
      ['The Last of Us', '2023– · HBO. Joel und Ellie in einer Pilz-Zombie-Welt. Basierend auf dem Videospiel.', '🍄', 'The Last of Us (TV series)', 8.8],
      ['Succession', '2018–23 · 4 Staffeln. Roy-Familie kämpft um Kontrolle eines Medienimperiums.', '💼', 'Succession (TV series)', 8.9],
      ['Ozark', '2017–22 · 4 Staffeln. Finanzberater wäscht Geld für ein Kartell in den Ozark Mountains.', '💵', 'Ozark (TV series)', 8.5],
      ['Seinfeld', '1989–98 · 9 Staffeln. „Die Show über nichts" — New Yorker Alltag als Comedy-Genie.', '🥨', 'Seinfeld', 8.9],
      ['The Walking Dead', '2010–22 · 11 Staffeln. Überlebenskampf in einer Zombie-Apokalypse.', '🧟', 'The Walking Dead (TV series)', 8.1],
      ['Lost', '2004–10 · 6 Staffeln. Flugzeugabsturz auf mysteriöser Insel voller Geheimnisse.', '🏝️', 'Lost (TV series)', 8.3],
      ['Prison Break', '2005–17 · 5 Staffeln. Ingenieur lässt sich einsperren, um seinen Bruder zu befreien.', '🔓', 'Prison Break', 8.3],
    ],
  },

  songs: {
    name: 'Songs', emoji: '🎵',
    criterion: 'Spotify-Streams (Milliarden)',
    criterionDesc: 'Sortiere nach Spotify-Streams (meiste = Platz 1)',
    items: [
      ['Bohemian Rhapsody', 'Queen · 1975. 6-Minuten Rock-Oper — Freddie Mercurys Meisterwerk.', '👑', 'Bohemian Rhapsody', 2.1],
      ['Imagine', 'John Lennon · 1971. Hymne für Frieden und eine Welt ohne Grenzen.', '☮️', 'Imagine (John Lennon song)', 1.1],
      ['Billie Jean', 'Michael Jackson · 1982. Der Song, bei dem MJ erstmals den Moonwalk zeigte.', '🕺', 'Billie Jean', 1.5],
      ['Smells Like Teen Spirit', 'Nirvana · 1991. Der Song, der Grunge zum Mainstream machte.', '🎸', 'Smells Like Teen Spirit', 2.0],
      ['Hotel California', 'Eagles · 1977. Mysteriöses Meisterwerk über ein Hotel, das man nie verlassen kann.', '🏨', 'Hotel California', 1.2],
      ['Stairway to Heaven', 'Led Zeppelin · 1971. 8-minütiges Epos bis zum explosiven Gitarrensolo.', '🪜', 'Stairway to Heaven', 0.8],
      ['Like a Rolling Stone', 'Bob Dylan · 1965. Revolutionierte die Rockmusik.', '🪨', 'Like a Rolling Stone', 0.5],
      ['Hey Jude', 'The Beatles · 1968. McCartneys Aufmunterung mit legendärem „Na-na-na" Outro.', '🎹', 'Hey Jude', 1.0],
      ['Lose Yourself', 'Eminem · 2002. Aus 8 Mile. Erster Hip-Hop-Song mit Oscar.', '🎤', 'Lose Yourself', 1.8],
      ['Shape of You', 'Ed Sheeran · 2017. Über 3,5 Mrd. Spotify-Streams.', '🎶', 'Shape of You', 4.0],
      ['Blinding Lights', 'The Weeknd · 2019. 80er-Synthie trifft modernen Pop. Meistgestreamt auf Spotify.', '✨', 'Blinding Lights', 4.6],
      ['Rolling in the Deep', 'Adele · 2010. Kraftvolle Stimme, gebrochenes Herz. Grammy Song of the Year.', '🔥', 'Rolling in the Deep', 1.5],
      ['Thriller', 'Michael Jackson · 1982. Meistverkauftes Album aller Zeiten. Ikonisches Zombievideo.', '🧟', 'Thriller (song)', 1.2],
      ['Sweet Child O\' Mine', 'Guns N\' Roses · 1987. Slashs legendäres Gitarrenriff.', '🎸', "Sweet Child o' Mine", 1.4],
      ['Don\'t Stop Believin\'', 'Journey · 1981. Ultimativer Feel-Good-Rock-Song.', '🌅', "Don't Stop Believin'", 1.7],
      ['Superstition', 'Stevie Wonder · 1972. Funky Clavinet-Riff. Grammy-Gewinner.', '🎹', 'Superstition (song)', 0.9],
      ['Wonderwall', 'Oasis · 1995. Britpop-Hymne, gespielt auf jeder Akustikgitarre der Welt.', '🎸', 'Wonderwall (song)', 1.9],
      ['Creep', 'Radiohead · 1992. „I\'m a creep, I\'m a weirdo." Außenseiter-Song einer Generation.', '🥀', 'Creep (Radiohead song)', 1.6],
      ['Somebody That I Used to Know', 'Gotye · 2011. Der perfekte Trennungssong mit Kimbra.', '💔', 'Somebody That I Used to Know', 1.8],
      ['Mr. Brightside', 'The Killers · 2003. Seit 20+ Jahren in den UK-Charts. Unsterblicher Indie-Hit.', '🌟', 'Mr. Brightside', 2.3],
      ['Take On Me', 'a-ha · 1985. Norwegischer Synthie-Pop mit legendärem Animationsvideo.', '✏️', 'Take On Me', 1.6],
      ['Dancing Queen', 'ABBA · 1976. Disco-Hymne schlechthin. Nr. 1 in 18 Ländern.', '💃', 'Dancing Queen', 1.4],
      ['Under Pressure', 'Queen & Bowie · 1981. Zwei Legenden, eine ikonische Basslinie.', '💎', 'Under Pressure', 1.1],
      ['Nothing Else Matters', 'Metallica · 1991. Die sensible Seite von Metal.', '🖤', 'Nothing Else Matters', 1.7],
      ['Purple Rain', 'Prince · 1984. 8 Minuten Emotion und eines der besten Gitarrensoli aller Zeiten.', '🌧️', 'Purple Rain (song)', 0.7],
    ],
  },

  sportler: {
    name: 'Sportler', emoji: '🏆',
    criterion: 'Major-Titel / Medaillen',
    criterionDesc: 'Sortiere nach Anzahl gewonnener Titel & Medaillen (meiste = Platz 1)',
    items: [
      ['Michael Jordan', 'Basketball · 6× NBA-Champion mit den Bulls. Bester Basketballer aller Zeiten.', '🏀', 'Michael Jordan', 6],
      ['Lionel Messi', 'Fußball · 8× Ballon d\'Or, Weltmeister 2022. Bester Fußballer der Geschichte.', '⚽', 'Lionel Messi', 44],
      ['Cristiano Ronaldo', 'Fußball · 5× Champions League, über 900 Karriere-Tore.', '⚽', 'Cristiano Ronaldo', 34],
      ['Usain Bolt', 'Sprint · 8× Olympia-Gold. 100m in 9,58s — Weltrekord bis heute.', '⚡', 'Usain Bolt', 8],
      ['Muhammad Ali', 'Boxen · 3× Weltmeister. „Float like a butterfly, sting like a bee."', '🥊', 'Muhammad Ali', 3],
      ['Roger Federer', 'Tennis · 20 Grand-Slam-Titel. Eleganz und Fairplay auf dem Platz.', '🎾', 'Roger Federer', 20],
      ['LeBron James', 'Basketball · 4× NBA-Champion, 4× MVP. Allzeit-Topscorer der NBA.', '🏀', 'LeBron James', 4],
      ['Pelé', 'Fußball · 3× Weltmeister. Über 1.000 Tore. „O Rei" — der König.', '👑', 'Pelé', 3],
      ['Serena Williams', 'Tennis · 23 Grand-Slam-Titel im Einzel — Rekord der Open Era.', '🎾', 'Serena Williams', 23],
      ['Michael Schumacher', 'Formel 1 · 7× Weltmeister, 91 Siege. Dominierte die F1 wie kein anderer.', '🏎️', 'Michael Schumacher', 7],
      ['Lewis Hamilton', 'Formel 1 · 7× Weltmeister, über 100 Siege.', '🏁', 'Lewis Hamilton', 7],
      ['Tiger Woods', 'Golf · 15 Major-Titel. Machte Golf zum weltweiten Massenphänomen.', '⛳', 'Tiger Woods', 15],
      ['Diego Maradona', 'Fußball · WM 1986: „Hand Gottes" und „Tor des Jahrhunderts" im selben Spiel.', '🇦🇷', 'Diego Maradona', 1],
      ['Kobe Bryant', 'Basketball · 5× NBA-Champion mit den LA Lakers. „Mamba Mentality."', '🐍', 'Kobe Bryant', 5],
      ['Wayne Gretzky', 'Eishockey · „The Great One" — über 60 NHL-Rekorde.', '🏒', 'Wayne Gretzky', 4],
      ['Tom Brady', 'Football · 7× Super-Bowl-Champion. Erfolgreichster NFL-Spieler aller Zeiten.', '🏈', 'Tom Brady', 7],
      ['Nadia Comăneci', 'Turnen · Erste perfekte 10,0 bei Olympia 1976. Gerade 14 Jahre alt.', '🤸', 'Nadia Comăneci', 5],
      ['Zinédine Zidane', 'Fußball · Weltmeister 1998, 3× FIFA-Weltfußballer.', '🇫🇷', 'Zinedine Zidane', 1],
      ['Michael Phelps', 'Schwimmen · 23× Olympia-Gold — erfolgreichster Olympionike aller Zeiten.', '🏊', 'Michael Phelps', 28],
      ['Novak Djokovic', 'Tennis · 24 Grand-Slam-Titel — Rekordhalter bei den Herren.', '🎾', 'Novak Djokovic', 24],
      ['Mike Tyson', 'Boxen · Jüngster Schwergewichts-Weltmeister mit 20 Jahren.', '🥊', 'Mike Tyson', 2],
      ['Franz Beckenbauer', 'Fußball · „Der Kaiser" — Weltmeister als Spieler und Trainer.', '🇩🇪', 'Franz Beckenbauer', 2],
      ['Rafael Nadal', 'Tennis · 22 Grand-Slams, 14× French Open — „König des Sand".', '🏆', 'Rafael Nadal', 22],
      ['Simone Biles', 'Turnen · 7× Olympia-Gold, 30× WM-Gold. Beste Turnerin aller Zeiten.', '🤸', 'Simone Biles', 37],
      ['Carl Lewis', 'Leichtathletik · 9× Olympia-Gold in Sprint und Weitsprung.', '🏃', 'Carl Lewis', 9],
    ],
  },

  staedte: {
    name: 'Städte', emoji: '🌍',
    criterion: 'Einwohnerzahl (Metropolregion, Mio.)',
    criterionDesc: 'Sortiere nach Einwohnerzahl (größte = Platz 1)',
    items: [
      ['New York', '8,3 Mio. · Freiheitsstatue, Broadway, Wall Street, Central Park.', '🗽', 'New York City', 20.1],
      ['Paris', '2,1 Mio. · Stadt der Liebe — Eiffelturm, Louvre, Croissants.', '🗼', 'Paris', 13.0],
      ['Tokio', '14 Mio. · Größte Metropolregion. Hightech trifft uralte Tempel.', '🏯', 'Tokyo', 37.4],
      ['London', '9 Mio. · Big Ben, Buckingham Palace, Premier League.', '🇬🇧', 'London', 14.8],
      ['Rom', '2,8 Mio. · Ewige Stadt — Kolosseum, Vatikan, 3.000 Jahre Geschichte.', '🏛️', 'Rome', 4.3],
      ['Barcelona', '1,6 Mio. · Gaudís Sagrada Familia, La Rambla, Strand.', '🏖️', 'Barcelona', 5.6],
      ['Dubai', '3,5 Mio. · Burj Khalifa (828m), künstliche Inseln, Luxus in der Wüste.', '🏙️', 'Dubai', 3.5],
      ['Istanbul', '16 Mio. · Brücke zwischen Europa und Asien. Hagia Sophia, Bosporus.', '🕌', 'Istanbul', 15.8],
      ['Sydney', '5,3 Mio. · Opernhaus, Harbour Bridge und Bondi Beach.', '🌊', 'Sydney', 5.3],
      ['Rio de Janeiro', '6,7 Mio. · Christusstatue, Copacabana, Karneval.', '🎉', 'Rio de Janeiro', 13.6],
      ['Amsterdam', '900.000 · Grachten, Fahrräder, Van Gogh Museum.', '🚲', 'Amsterdam', 2.5],
      ['Berlin', '3,7 Mio. · Brandenburger Tor, Clubszene, Geschichte.', '🐻', 'Berlin', 6.1],
      ['Wien', '1,9 Mio. · Lebenswerteste Stadt. Schnitzel, Kaffeehäuser, Klassik.', '🎻', 'Vienna', 2.0],
      ['Prag', '1,3 Mio. · Goldene Stadt — Karlsbrücke, Astronomische Uhr.', '🍺', 'Prague', 2.7],
      ['Singapur', '5,9 Mio. · Reichste Stadt Asiens. Marina Bay Sands, Streetfood.', '🌴', 'Singapore', 5.9],
      ['Bangkok', '11 Mio. · Tempel, Tuk-Tuks, legendäres Streetfood.', '🛕', 'Bangkok', 17.1],
      ['Lissabon', '550.000 · Hügelige Altstadt, Pastéis de Nata, Fado-Musik.', '🚃', 'Lisbon', 3.0],
      ['Buenos Aires', '3 Mio. · Tango-Hauptstadt. La Boca, Steakhäuser.', '💃', 'Buenos Aires', 15.4],
      ['Kapstadt', '4,6 Mio. · Tafelberg, Robben Island, atemberaubende Küste.', '🏔️', 'Cape Town', 4.6],
      ['San Francisco', '870.000 · Golden Gate Bridge, Silicon Valley, Cable Cars.', '🌉', 'San Francisco', 4.7],
      ['München', '1,5 Mio. · Oktoberfest, Englischer Garten, FC Bayern.', '🍻', 'Munich', 2.9],
      ['Venedig', '260.000 · Gondeln, Markusplatz und bunte Murano-Inseln.', '🚣', 'Venice', 0.3],
      ['Kyoto', '1,5 Mio. · 2.000 Tempel, Geisha-Kultur, Zen-Gärten.', '⛩️', 'Kyoto', 1.5],
      ['Marrakesch', '1 Mio. · Djemaa el-Fna, Souks, Riads und Farben.', '🧡', 'Marrakech', 1.3],
      ['Havanna', '2,1 Mio. · Oldtimer, Rum, Salsa und koloniale Architektur.', '🚗', 'Havana', 2.1],
      ['Vancouver', '2,5 Mio. · Berge, Meer und Wolkenkratzer.', '🏔️', 'Vancouver', 2.6],
      ['Stockholm', '1 Mio. · Nordisches Design, 14 Inseln, ABBA-Museum.', '🇸🇪', 'Stockholm', 2.4],
      ['Athen', '3,1 Mio. · Wiege der Demokratie. Akropolis, Parthenon.', '🏛️', 'Athens', 3.2],
      ['Seoul', '9,7 Mio. · K-Pop, K-Food, Hightech und Paläste.', '🇰🇷', 'Seoul', 25.5],
    ],
  },

  essen: {
    name: 'Essen', emoji: '🍕',
    criterion: 'Google Trends Score (weltweit)',
    criterionDesc: 'Sortiere nach weltweiter Beliebtheit / Google-Suchen (meiste = Platz 1)',
    items: [
      ['Pizza', 'Italien · Margherita 1889 in den Farben der italienischen Flagge.', '🍕', 'Pizza', 100],
      ['Sushi', 'Japan · Im 19. Jh. in Tokio als Fast Food erfunden.', '🍣', 'Sushi', 68],
      ['Burger', 'USA · McDonald\'s verkauft täglich 6,5 Millionen Stück.', '🍔', 'Hamburger', 82],
      ['Pasta', 'Italien · Über 350 verschiedene Formen. Nationalstolz.', '🍝', 'Pasta', 72],
      ['Tacos', 'Mexiko · Mais-Tortilla mit Fleisch, Salsa, Koriander, Limette.', '🌮', 'Taco', 48],
      ['Schnitzel', 'Österreich · Paniertes Kalbfleisch. Wiener Schnitzel ist UNESCO-Kulturerbe.', '🥩', 'Wiener schnitzel', 18],
      ['Ramen', 'Japan · Nudelsuppe mit Chashu-Schweinefleisch und Ei. Japans Soulfood.', '🍜', 'Ramen', 55],
      ['Döner Kebab', 'Türkei/Berlin · Kadir Nurman eröffnete 1972 den ersten Stand in Berlin.', '🥙', 'Doner kebab', 30],
      ['Paella', 'Spanien · Reisgericht mit Safran aus Valencia.', '🥘', 'Paella', 22],
      ['Pad Thai', 'Thailand · Gebratene Reisnudeln mit Garnelen und Erdnüssen. Nationalgericht.', '🍜', 'Pad thai', 25],
      ['Steak', 'Weltweit · Argentinien und USA streiten um das beste der Welt.', '🥩', 'Steak', 60],
      ['Currywurst', 'Berlin · Erfunden 1949 von Herta Heuwer. Jährlich 800 Mio. Stück.', '🌭', 'Currywurst', 8],
      ['Dim Sum', 'China · Kleine gedämpfte Häppchen. Kantonesische Teehaus-Tradition.', '🥟', 'Dim sum', 20],
      ['Croissant', 'Frankreich · Butteriges Blätterteig-Gebäck. Eigentlich aus Wien.', '🥐', 'Croissant', 35],
      ['Pho', 'Vietnam · Aromatische Reisnudelsuppe mit Rindfleisch und Kräutern.', '🍲', 'Pho', 28],
      ['Fish & Chips', 'UK · Frittierter Fisch im Bierteig mit Pommes seit dem 19. Jh.', '🐟', 'Fish and chips', 20],
      ['Gyros', 'Griechenland · Fleisch vom Drehspieß mit Tzatziki und Pita.', '🥙', 'Gyros', 15],
      ['Biryani', 'Indien · Aromatisches Reisgericht mit Gewürzen und Safran.', '🍛', 'Biryani', 45],
      ['Ceviche', 'Peru · Roher Fisch in Limettensaft „gegart". Perus Stolz.', '🐟', 'Ceviche', 12],
      ['Poutine', 'Kanada · Pommes mit Bratensauce und Cheese Curds.', '🍟', 'Poutine', 10],
      ['Falafel', 'Naher Osten · Frittierte Kichererbsen-Bällchen. Veganer Klassiker.', '🧆', 'Falafel', 22],
      ['Pierogi', 'Polen · Gefüllte Teigtaschen mit Kartoffeln, Quark oder Fleisch.', '🥟', 'Pierogi', 12],
      ['Tiramisu', 'Italien · Mascarpone, Espresso, Kakao. „Zieh mich hoch."', '🍰', 'Tiramisu', 38],
      ['Crêpes', 'Frankreich · Hauchdünne Pfannkuchen — süß oder herzhaft.', '🥞', 'Crêpe', 30],
      ['Pulled Pork', 'USA · Stundenlang geräuchertes Schweinefleisch. BBQ-Kultur.', '🐷', 'Pulled pork', 15],
      ['Lasagne', 'Italien · Geschichtete Pasta mit Bolognese und Béchamel.', '🧀', 'Lasagne', 40],
      ['Brezen', 'Bayern · Laugengebäck mit Salz. Biergartenbegleiter.', '🥨', 'Pretzel', 16],
      ['Poke Bowl', 'Hawaii · Gewürfelter Fisch auf Reis. Weltweiter Health-Food-Trend.', '🥗', 'Poke (dish)', 18],
    ],
  },

  automarken: {
    name: 'Automarken', emoji: '🚗',
    criterion: 'Markenwert (Mrd. USD, 2024)',
    criterionDesc: 'Sortiere nach Markenwert in Milliarden USD (höchster = Platz 1)',
    items: [
      ['Mercedes-Benz', 'Gegr. 1926 · Stuttgart. Erfinder des Automobils (1886).', '⭐', 'Mercedes-Benz', 56.3],
      ['BMW', 'Gegr. 1916 · München. „Freude am Fahren."', '🔵', 'BMW', 38.2],
      ['Audi', 'Gegr. 1909 · Ingolstadt. „Vorsprung durch Technik."', '⚙️', 'Audi', 14.7],
      ['Porsche', 'Gegr. 1931 · Stuttgart. Der 911 — Sportwagen-Ikone seit 1963.', '🏁', 'Porsche', 37.2],
      ['Ferrari', 'Gegr. 1947 · Maranello. Das springende Pferd — Formel 1 und Traumauto.', '🐎', 'Ferrari', 12.4],
      ['Lamborghini', 'Gegr. 1963 · Aus Trotz gegen Enzo Ferrari. Stier-Logo, V12, Extravaganz.', '🐂', 'Lamborghini', 4.5],
      ['Tesla', 'Gegr. 2003 · Kalifornien. Elon Musks E-Auto-Revolution.', '⚡', 'Tesla, Inc.', 66.2],
      ['Toyota', 'Gegr. 1937 · Japan. Größter Autobauer der Welt.', '🇯🇵', 'Toyota', 64.7],
      ['Volkswagen', 'Gegr. 1937 · Wolfsburg. Der Käfer ist das meistverkaufte Auto der Geschichte.', '🚙', 'Volkswagen', 15.1],
      ['Ford', 'Gegr. 1903 · Detroit. Henry Ford erfand das Fließband. Der Mustang ist Legende.', '🐴', 'Ford Motor Company', 10.4],
      ['Chevrolet', 'Gegr. 1911 · Detroit. Corvette, Camaro — Amerikas beliebteste Marke.', '🇺🇸', 'Chevrolet', 7.8],
      ['Aston Martin', 'Gegr. 1913 · England. James Bonds Auto der Wahl.', '🕶️', 'Aston Martin', 2.5],
      ['Bentley', 'Gegr. 1919 · England. Handgefertigter Luxus aus Crewe.', '🎩', 'Bentley', 3.8],
      ['Rolls-Royce', 'Gegr. 1906 · England. Spirit of Ecstasy. Ultimativer Luxus.', '👑', 'Rolls-Royce Motor Cars', 5.2],
      ['Maserati', 'Gegr. 1914 · Bologna. Dreizack-Logo. Italienischer Gran Turismo.', '🔱', 'Maserati', 1.5],
      ['McLaren', 'Gegr. 1963 · England. Vom F1-Rennstall zum Supersportwagen-Hersteller.', '🏎️', 'McLaren Automotive', 2.0],
      ['Bugatti', 'Gegr. 1909 · Frankreich. Chiron: über 400 km/h. Ab 3 Mio. Euro.', '💨', 'Bugatti', 1.8],
      ['Jaguar', 'Gegr. 1922 · England. E-Type: „Schönstes Auto aller Zeiten" (Enzo Ferrari).', '🐆', 'Jaguar Cars', 3.0],
      ['Land Rover', 'Gegr. 1948 · England. Vom Farmfahrzeug zur Geländeikone.', '🌍', 'Land Rover', 5.5],
      ['Volvo', 'Gegr. 1927 · Schweden. Erfinder des Dreipunkt-Gurts (1959).', '🛡️', 'Volvo Cars', 7.0],
      ['Alfa Romeo', 'Gegr. 1910 · Mailand. Italiens leidenschaftlichste Marke.', '🇮🇹', 'Alfa Romeo', 1.2],
      ['Lexus', 'Gegr. 1989 · Japan. Toyotas Luxusmarke. Leise Perfektion.', '💎', 'Lexus', 6.2],
      ['Subaru', 'Gegr. 1953 · Japan. Allrad-Spezialist. Rallye-Champion.', '🌟', 'Subaru', 3.5],
      ['Mazda', 'Gegr. 1920 · Hiroshima. MX-5 ist der meistverkaufte Roadster.', '🔴', 'Mazda', 3.3],
      ['Mini', 'Gegr. 1959 · England. Kultstatus seit den Swinging Sixties.', '🇬🇧', 'Mini (marque)', 4.0],
      ['Jeep', 'Gegr. 1941 · USA. Im 2. Weltkrieg geboren. Freiheit und Offroad.', '🪖', 'Jeep', 8.0],
      ['Dodge', 'Gegr. 1900 · USA. Challenger, Charger — pure Muscle-Car-Power.', '💪', 'Dodge', 3.2],
      ['Hyundai', 'Gegr. 1967 · Südkorea. Vom Billigauto zur Design-Marke.', '🇰🇷', 'Hyundai', 18.5],
    ],
  },

  videospiele: {
    name: 'Videospiele', emoji: '🎮',
    criterion: 'Metacritic Score',
    criterionDesc: 'Sortiere nach Metacritic-Wertung (höchste = Platz 1)',
    items: [
      ['Minecraft', '2011 · Über 300 Mio. verkauft — meistverkauftes Spiel aller Zeiten.', '⛏️', 'Minecraft', 93],
      ['GTA V', '2013 · Über 200 Mio. verkauft. Open World in Los Santos.', '🚗', 'Grand Theft Auto V', 97],
      ['Zelda: Breath of the Wild', '2017 · Nintendo. Revolutionierte Open-World-Games.', '🗡️', 'The Legend of Zelda: Breath of the Wild', 97],
      ['Red Dead Redemption 2', '2018 · Rockstar. Wilder Westen in atemberaubender Detailtreue.', '🤠', 'Red Dead Redemption 2', 97],
      ['The Witcher 3', '2015 · CD Projekt Red. Riesige Fantasywelt, über 250 Stunden Content.', '🐺', 'The Witcher 3: Wild Hunt', 92],
      ['Super Mario Bros.', '1985 · Nintendo. Der Klempner, der die Videospielindustrie rettete.', '🍄', 'Super Mario Bros.', 85],
      ['Tetris', '1985 · In der Sowjetunion erfunden. Über 500 Mio. verkauft.', '🧱', 'Tetris', 83],
      ['God of War', '2018 · Kratos als Vater in der nordischen Mythologie. Game of the Year.', '⚡', 'God of War (2018 video game)', 94],
      ['Elden Ring', '2022 · FromSoftware. Story von George R.R. Martin. Über 25 Mio. verkauft.', '💍', 'Elden Ring', 96],
      ['Fortnite', '2017 · 400 Mio. registrierte Spieler. Battle Royale einer Generation.', '🪂', 'Fortnite', 78],
      ['The Last of Us', '2013 · Naughty Dog. Emotionalste Story der Gaming-Geschichte.', '🍄', 'The Last of Us', 95],
      ['Dark Souls', '2011 · FromSoftware. „You Died" — das Genre der brutalen Bosskämpfe.', '🔥', 'Dark Souls', 89],
      ['Skyrim', '2011 · Bethesda. Riesige Fantasywelt mit Drachen und hunderten Quests.', '🐉', 'The Elder Scrolls V: Skyrim', 94],
      ['Portal 2', '2011 · Valve. Geniales Puzzle-Spiel. „The cake is a lie."', '🕳️', 'Portal 2', 95],
      ['Half-Life 2', '2004 · Valve. Revolutionierte Physik in Spielen.', '🔬', 'Half-Life 2', 96],
      ['Resident Evil 4', '2005 · Capcom. Definierte Survival Horror neu.', '🧟', 'Resident Evil 4', 96],
      ['FIFA / EA FC', '1993– · Über 325 Mio. verkauft in der Reihe.', '⚽', 'EA Sports FC', 75],
      ['Call of Duty: Modern Warfare', '2007 · Revolutionierte den Online-Shooter.', '🎯', 'Call of Duty 4: Modern Warfare', 94],
      ['Halo', '2001 · Master Chief rettete die Xbox. Milliarden-Franchise.', '🪖', 'Halo (franchise)', 97],
      ['Pokémon', '1996 · „Schnapp sie dir alle!" Größtes Medien-Franchise der Welt.', '⚡', 'Pokémon Red and Blue', 89],
      ['Among Us', '2018 · Wer ist der Verräter? Ging 2020 viral. 500 Mio. Spieler.', '🔪', 'Among Us', 85],
      ['Cyberpunk 2077', '2020 · Night City der Zukunft. Nach Updates ein Meisterwerk.', '🌃', 'Cyberpunk 2077', 86],
      ['Stardew Valley', '2016 · Ein Entwickler baute allein das gemütlichste Farm-Spiel.', '🌾', 'Stardew Valley', 89],
      ['Mario Kart', '1992– · Das Rennspiel, das Freundschaften zerstört.', '🏎️', 'Mario Kart', 92],
      ['Animal Crossing', '2001– · Entspanntes Inselleben. New Horizons: 44 Mio. verkauft.', '🏝️', 'Animal Crossing: New Horizons', 90],
      ['Doom', '1993 · id Software. Der Urknall des Ego-Shooters.', '😈', 'Doom (1993 video game)', 85],
      ['BioShock', '2007 · „Would you kindly?" Unterwasser-Dystopie Rapture.', '💧', 'BioShock', 96],
    ],
  },

  laender: {
    name: 'Länder', emoji: '🗺️',
    criterion: 'Touristen pro Jahr (Mio.)',
    criterionDesc: 'Sortiere nach internationalen Touristen pro Jahr (meiste = Platz 1)',
    items: [
      ['Italien', '60 Mio. · Meiste UNESCO-Welterbestätten. Pizza, Pasta, Dolce Vita.', '🇮🇹', 'flag:it', 57.0],
      ['Japan', '125 Mio. · Hightech und Tradition. Sushi, Anime, Kirschblüten.', '🇯🇵', 'flag:jp', 25.0],
      ['Frankreich', '68 Mio. · Meistbesuchtes Land der Welt. Wein, Käse, Kultur.', '🇫🇷', 'flag:fr', 100.0],
      ['Spanien', '48 Mio. · Tapas, Flamenco, Strände. Nr. 2 der Touristen.', '🇪🇸', 'flag:es', 85.0],
      ['USA', '335 Mio. · Drittgrößtes Land. Hollywood, Silicon Valley, Grand Canyon.', '🇺🇸', 'flag:us', 66.5],
      ['Brasilien', '215 Mio. · Amazonas, Karneval, 5× Fußball-Weltmeister.', '🇧🇷', 'flag:br', 6.6],
      ['Australien', '26 Mio. · Kontinent und Land. Great Barrier Reef, Koalas.', '🇦🇺', 'flag:au', 9.5],
      ['Kanada', '40 Mio. · Zweitgrößtes Land. Rocky Mountains, Ahornsirup.', '🇨🇦', 'flag:ca', 27.0],
      ['Deutschland', '84 Mio. · Größte Volkswirtschaft Europas. Bier, Autos.', '🇩🇪', 'flag:de', 37.5],
      ['Griechenland', '10 Mio. · Wiege der Demokratie. 6.000 Inseln, Akropolis.', '🇬🇷', 'flag:gr', 33.0],
      ['Thailand', '72 Mio. · „Land des Lächelns." Traumstrände, Tempel.', '🇹🇭', 'flag:th', 28.0],
      ['Mexiko', '130 Mio. · Azteken-Erbe, Tacos, Tequila. 35+ UNESCO-Stätten.', '🇲🇽', 'flag:mx', 45.0],
      ['Neuseeland', '5 Mio. · Herr-der-Ringe-Drehorte. Fjorde, Vulkane, Māori.', '🇳🇿', 'flag:nz', 3.8],
      ['Norwegen', '5,5 Mio. · Fjorde, Nordlichter. Höchster Lebensstandard.', '🇳🇴', 'flag:no', 6.3],
      ['Portugal', '10 Mio. · Seefahrernation. Pastéis de Nata, Algarve.', '🇵🇹', 'flag:pt', 26.5],
      ['Schweiz', '9 Mio. · Alpen, Schokolade, Uhren, direkte Demokratie.', '🇨🇭', 'flag:ch', 12.0],
      ['Österreich', '9 Mio. · Mozart, Wiener Schnitzel, Skifahren.', '🇦🇹', 'flag:at', 32.0],
      ['Südkorea', '52 Mio. · K-Pop, Samsung, Kimchi. In 60 Jahren zur Hightech-Nation.', '🇰🇷', 'flag:kr', 11.0],
      ['Argentinien', '46 Mio. · Tango, Steak, Patagonien. Messi-Mania.', '🇦🇷', 'flag:ar', 7.4],
      ['Island', '380.000 · Vulkane, Geysire, Gletscher, Nordlichter.', '🇮🇸', 'flag:is', 2.2],
      ['Kroatien', '3,8 Mio. · Adriaküste, Dubrovnik, Plitvicer Seen.', '🇭🇷', 'flag:hr', 19.5],
      ['Irland', '5 Mio. · Grüne Insel. Guinness, Cliffs of Moher.', '🇮🇪', 'flag:ie', 11.0],
      ['Türkei', '85 Mio. · Brücke zweier Kontinente. Hagia Sophia, Kebab.', '🇹🇷', 'flag:tr', 56.0],
      ['Indien', '1,4 Mrd. · Bevölkerungsreichstes Land. Taj Mahal, Bollywood.', '🇮🇳', 'flag:in', 10.0],
      ['Ägypten', '110 Mio. · Pyramiden von Gizeh — letztes Weltwunder der Antike.', '🇪🇬', 'flag:eg', 13.0],
      ['Marokko', '37 Mio. · Sahara, Marrakesch, Berberkultur.', '🇲🇦', 'flag:ma', 14.5],
      ['Vietnam', '100 Mio. · Halong-Bucht, Pho, boomt als Reiseziel.', '🇻🇳', 'flag:vn', 12.6],
      ['Südafrika', '60 Mio. · Safaris, Kapstadt, Mandela. 11 Amtssprachen.', '🇿🇦', 'flag:za', 8.5],
    ],
  },

  fussball: {
    name: 'Fußballvereine', emoji: '⚽',
    criterion: 'Champions-League-Titel',
    criterionDesc: 'Sortiere nach Anzahl Champions-League- / Europapokal-Titel (meiste = Platz 1)',
    items: [
      ['Real Madrid', 'Gegr. 1902 · 15× Champions League — Rekordhalter.', '🤍', 'Real Madrid CF', 15],
      ['FC Barcelona', 'Gegr. 1899 · „Més que un club." Messi, Cruyff, Tiki-Taka.', '🔴', 'FC Barcelona', 5],
      ['Bayern München', 'Gegr. 1900 · 33× Deutscher Meister, 6× Champions League.', '🔴', 'FC Bayern Munich', 6],
      ['Manchester United', 'Gegr. 1878 · Old Trafford, Ferguson-Ära, 13 Premier-League-Titel.', '🔴', 'Manchester United F.C.', 3],
      ['Liverpool FC', 'Gegr. 1892 · Anfield, „You\'ll Never Walk Alone." 6× CL.', '🔴', 'Liverpool F.C.', 6],
      ['Juventus Turin', 'Gegr. 1897 · 36× Scudetto. „Die alte Dame."', '⬛', 'Juventus F.C.', 2],
      ['AC Milan', 'Gegr. 1899 · 7× Champions League. Baresi, Maldini.', '🔴', 'AC Milan', 7],
      ['Paris Saint-Germain', 'Gegr. 1970 · Katarische Eigentümer. Neymar, Mbappé.', '🔵', 'Paris Saint-Germain F.C.', 0],
      ['Borussia Dortmund', 'Gegr. 1909 · „Gelbe Wand" — 25.000 Stehplätze, lauteste Fans.', '💛', 'Borussia Dortmund', 1],
      ['Chelsea FC', 'Gegr. 1905 · 2× Champions League. Stamford Bridge.', '🔵', 'Chelsea F.C.', 2],
      ['Arsenal', 'Gegr. 1886 · „The Invincibles" 2003/04 — ohne Niederlage.', '🔴', 'Arsenal F.C.', 0],
      ['Manchester City', 'Gegr. 1880 · Guardiola. 2023 Triple: PL, FA Cup, CL.', '🩵', 'Manchester City F.C.', 1],
      ['Inter Mailand', 'Gegr. 1908 · 3× Champions League. Milans anderer Gigant.', '⚫', 'Inter Milan', 3],
      ['Ajax Amsterdam', 'Gegr. 1900 · Cruyff-Schule. Legendäre Jugendakademie.', '🔴', 'AFC Ajax', 4],
      ['Atletico Madrid', 'Gegr. 1903 · Simeones Kampfgeist. Madrids Arbeiterclub.', '🔴', 'Atlético Madrid', 0],
      ['Tottenham Hotspur', 'Gegr. 1882 · Nord-London-Rivale. Milliarden-Stadion.', '⚪', 'Tottenham Hotspur F.C.', 0],
      ['AS Rom', 'Gegr. 1927 · Tottis Stadt. Stadio Olimpico.', '🟡', 'AS Roma', 0],
      ['SSC Neapel', 'Gegr. 1926 · Maradonas Verein. Scudetto 2023 nach 33 Jahren.', '🔵', 'S.S.C. Napoli', 0],
      ['Benfica Lissabon', 'Gegr. 1904 · 37× Meister. Eusébios Verein.', '🔴', 'S.L. Benfica', 2],
      ['FC Porto', 'Gegr. 1893 · 2× CL-Sieger. Mourinhos Durchbruch 2004.', '🔵', 'FC Porto', 2],
      ['Celtic Glasgow', 'Gegr. 1887 · „Paradise." 1967 erster britischer Europapokalsieger.', '🍀', 'Celtic F.C.', 1],
      ['Olympique Marseille', 'Gegr. 1899 · Einziger französischer CL-Sieger (1993).', '⚪', 'Olympique de Marseille', 1],
      ['Galatasaray', 'Gegr. 1905 · Istanbuls größter Verein. UEFA-Cup 2000.', '🟡', 'Galatasaray S.K. (football)', 0],
      ['Flamengo', 'Gegr. 1895 · 40 Mio. Fans — größte Fanbasis der Welt.', '🔴', 'CR Flamengo', 0],
      ['Boca Juniors', 'Gegr. 1905 · La Bombonera — lautestes Stadion Südamerikas.', '💛', 'Boca Juniors', 0],
      ['RB Leipzig', 'Gegr. 2009 · Red-Bull-Projekt — umstritten, aber erfolgreich.', '⚪', 'RB Leipzig', 0],
      ['Eintracht Frankfurt', 'Gegr. 1899 · Europa-League-Sieger 2022.', '🦅', 'Eintracht Frankfurt', 0],
      ['Schalke 04', 'Gegr. 1904 · Ruhrpott-Identität. „Blau und Weiß."', '🔵', 'FC Schalke 04', 0],
    ],
  },
};
